@ShopHub.Api_HostAddress = http://localhost:5091

POST {{ShopHub.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "correct-horse-battery"
}

###

POST {{ShopHub.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "correct-horse-battery"
}

###

GET {{ShopHub.Api_HostAddress}}/api/auth/me
Authorization: Bearer {{token}}

###
